prev_time = 0
count = 0
size = 256
agnostic_nms=False
conf_thres=float(0.5)  # confidence threshold
iou_thres=float(0.4)  # NMS IOU threshold
max_det=int(1000)
classes=[0]
track_keypoints = {}
track_labels = {}